export interface CuratedWordItem {
  word: string;
  definition: string;
  synonyms: string[];
  antonyms: string[];
}

// Compact structure to keep file generation reliable and fast
interface RawWord {
  w: string; // word
  d: string; // definition
  s: string; // synonym
  a: string; // antonym
}

const RAW_LIST: RawWord[] = [
  // A words
  { w: "Abandon", d: "To leave someone or something behind.", s: "Desert", a: "Stay" },
  { w: "Abundant", d: "Existing or available in large quantities.", s: "Plentiful", a: "Scarce" },
  { w: "Accurate", d: "Correct in all details; exact.", s: "Precise", a: "Wrong" },
  { w: "Achieve", d: "Reach or attain a desired objective by effort.", s: "Accomplish", a: "Fail" },
  { w: "Adamant", d: "Refusing to be persuaded or to change one's mind.", s: "Stubborn", a: "Flexible" },
  { w: "Adapt", d: "Make suitable for a new use or situation.", s: "Adjust", a: "Keep" },
  { w: "Adept", d: "Very skilled or proficient at something.", s: "Expert", a: "Clumsy" },
  { w: "Adore", d: "Love and respect someone deeply.", s: "Cherish", a: "Hate" },
  { w: "Advantage", d: "A condition or circumstance that puts one in a favorable position.", s: "Benefit", a: "Drawback" },
  { w: "Adversary", d: "One's opponent in a contest, conflict, or dispute.", s: "Rival", a: "Ally" },
  { w: "Affable", d: "Friendly, good-natured, or easy to talk to.", s: "Amiable", a: "Unfriendly" },
  { w: "Aggressive", d: "Ready or likely to attack or confront.", s: "Hostile", a: "Gentle" },
  { w: "Agile", d: "Able to move quickly and easily.", s: "Nimble", a: "Stiff" },
  { w: "Alarm", d: "An anxious awareness of danger.", s: "Frighten", a: "Soothe" },
  { w: "Alleviate", d: "Make suffering or a problem less severe.", s: "Relieve", a: "Aggravate" },
  { w: "Aloof", d: "Not friendly or forthcoming; cool and distant.", s: "Detached", a: "Sociable" },
  { w: "Alter", d: "Change or cause to change in character or composition.", s: "Modify", a: "Preserve" },
  { w: "Altruism", d: "The belief in or practice of disinterested and selfless concern for others.", s: "Generosity", a: "Selfishness" },
  { w: "Ambiguous", d: "Open to more than one interpretation; having a double meaning.", s: "Vague", a: "Clear" },
  { w: "Ambitious", d: "Having or showing a strong desire and determination to succeed.", s: "Driven", a: "Apathetic" },
  { w: "Amiable", d: "Having or displaying a friendly and pleasant manner.", s: "Warm", a: "Cold" },
  { w: "Ample", d: "Enough or more than enough; plentiful.", s: "Abundant", a: "Meager" },
  { w: "Amuse", d: "Provide interesting and enjoyable entertainment.", s: "Delight", a: "Bore" },
  { w: "Ancient", d: "Belonging to the very distant past.", s: "Antique", a: "Modern" },
  { w: "Animosity", d: "Strong hostility or friction.", s: "Enmity", a: "Goodwill" },
  { w: "Annoy", d: "Irritate or make someone slightly angry.", s: "Pester", a: "Calm" },
  { w: "Anticipate", d: "Regard as probable; expect or predict.", s: "Foresee", a: "Doubt" },
  { w: "Anxious", d: "Experiencing worry, unease, or nervousness.", s: "Apprehensive", a: "Confident" },
  { w: "Apathy", d: "Lack of interest, enthusiasm, or concern.", s: "Indifference", a: "Eagerness" },
  { w: "Apparel", d: "Clothing or personal attire.", s: "Attire", a: "None" },
  { w: "Appealing", d: "Attractive or interesting.", s: "Charming", a: "Repulsive" },
  { w: "Applaud", d: "Show approval or praise by clapping.", s: "Acclaim", a: "Boo" },
  { w: "Apron", d: "A protective garment worn over the front of one's clothes.", s: "Shield", a: "None" },
  { w: "Ardent", d: "Very enthusiastic or passionate.", s: "Fervent", a: "Indifferent" },
  { w: "Arduous", d: "Involving or requiring strenuous effort; difficult and tiring.", s: "Strenuous", a: "Easy" },
  { w: "Aroma", d: "A pleasant, characteristic smell.", s: "Fragrance", a: "Stench" },
  { w: "Articulate", d: "Having or showing the ability to speak fluently and coherently.", s: "Eloquent", a: "Muddled" },
  { w: "Ascend", d: "Go up or climb.", s: "Rise", a: "Descend" },
  { w: "Aspire", d: "Direct one's hopes or ambitions toward achieving something.", s: "Strive", a: "Surrender" },
  { w: "Astonish", d: "Surprise or impress someone greatly.", s: "Amaze", a: "Expect" },
  { w: "Astute", d: "Having or showing an ability to accurately assess situations.", s: "Shrewd", a: "Foolish" },
  { w: "Audacious", d: "Showing a willingness to take surprisingly bold risks.", s: "Daring", a: "Timid" },
  { w: "Aura", d: "The distinctive atmosphere that seems to surround a person.", s: "Vibe", a: "None" },
  { w: "Authentic", d: "Of undisputed origin; genuine.", s: "Real", a: "Fake" },
  { w: "Avarice", d: "Extreme greed for wealth or material gain.", s: "Greed", a: "Charity" },
  { w: "Avid", d: "Having or showing a keen interest in or enthusiasm for something.", s: "Eager", a: "Reluctant" },
  { w: "Avoid", d: "Keep away from or stop oneself from doing.", s: "Evade", a: "Seek" },
  { w: "Awesome", d: "Extremely impressive or daunting; inspiring great admiration.", s: "Magnificent", a: "Awful" },
  { w: "Baffled", d: "Totally bewildered or perplexed.", s: "Confused", a: "Clear" },
  { w: "Balance", d: "An even distribution of weight enabling stability.", s: "Equilibrium", a: "Unbalance" },
  { w: "Beacon", d: "A fire or light set up in a high position as a warning or guide.", s: "Signal", a: "None" },
  { w: "Beautiful", d: "Pleasing the senses or mind aesthetically.", s: "Lovely", a: "Ugly" },
  { w: "Belligerent", d: "Hostile and aggressive.", s: "Combative", a: "Peaceful" },
  { w: "Benevolent", d: "Well meaning and kindly.", s: "Generous", a: "Malevolent" },
  { w: "Benign", d: "Gentle and kindly; not harmful.", s: "Harmless", a: "Malignant" },
  { w: "Bequeath", d: "Leave a house or other property to a person by a will.", s: "Hand down", a: "Withhold" },
  { w: "Bewilder", d: "Cause someone to become perplexed and confused.", s: "Perplex", a: "Enlighten" },
  { w: "Bias", d: "Prejudice in favor of or against one thing, person, or group.", s: "Prejudice", a: "Fairness" },
  { w: "Blunt", d: "Having a flat or rounded end; simple and straightforward.", s: "Dull", a: "Sharp" },
  { w: "Bold", d: "Showing an ability to take risks; confident and courageous.", s: "Brave", a: "Fearful" },
  { w: "Bolster", d: "Support or strengthen; prop up.", s: "Reinforce", a: "Weaken" },
  { w: "Booster", d: "A source of help or encouragement.", s: "Supporter", a: "Hindrance" },
  { w: "Bountiful", d: "Large in quantity; abundant.", s: "Generous", a: "Scarce" },
  { w: "Brave", d: "Ready to face and endure danger or pain; showing courage.", s: "Courageous", a: "Cowardly" },
  { w: "Brevity", d: "Concise and exact use of words in writing or speech.", s: "Shortness", a: "Lengthiness" },
  { w: "Brief", d: "Of short duration; concise.", s: "Short", a: "Long" },
  { w: "Bright", d: "Giving off or reflecting much light; shining.", s: "Radiant", a: "Dark" },
  { w: "Brilliant", d: "Exceptionally clever or talented; shining brightly.", s: "Superb", a: "Stupid" },
  { w: "Brisk", d: "Active, fast, and energetic.", s: "Quick", a: "Slow" },
  { w: "Buoyant", d: "Able or apt to stay afloat or rise to the top; cheerful.", s: "Floating", a: "Sinking" },
  { w: "Busy", d: "Occupied with or concentrating on a particular activity.", s: "Active", a: "Idle" },
  { w: "Cabin", d: "A small wooden shelter or house.", s: "Cottage", a: "Mansion" },
  { w: "Cacophony", d: "A harsh, discordant mixture of sounds.", s: "Noise", a: "Harmony" },
  { w: "Calm", d: "Not showing or feeling nervousness, anger, or other emotions.", s: "Serene", a: "Stormy" },
  { w: "Camera", d: "A device for recording visual images.", s: "Recorder", a: "None" },
  { w: "Candor", d: "The quality of being open and honest in expression.", s: "Honesty", a: "Deceit" },
  { w: "Capricious", d: "Given to sudden and unaccountable changes of mood.", s: "Fickle", a: "Stable" },
  { w: "Captivate", d: "Attract and hold the interest and attention of.", s: "Enchant", a: "Disgust" },
  { w: "Capture", d: "Take into one's possession or control.", s: "Seize", a: "Release" },
  { w: "Cart", d: "A strong vehicle with two or four wheels, pulled by its handles.", s: "Wagon", a: "None" },
  { w: "Castle", d: "A large fortified building or mansion.", s: "Fortress", a: "Hut" },
  { w: "Catalyst", d: "A person or thing that precipitates an event or change.", s: "Spark", a: "Preventer" },
  { w: "Caution", d: "Care taken to avoid danger or mistakes.", s: "Prudence", a: "Recklessness" },
  { w: "Celebrate", d: "Acknowledge a significant event with a social gathering.", s: "Commemorate", a: "Mourn" },
  { w: "Celestial", d: "Positioned in or relating to the sky, or outer space.", s: "Heavenly", a: "Earthly" },
  { w: "Chalk", d: "A soft white limestone used for writing or drawing.", s: "Crayon", a: "None" },
  { w: "Champion", d: "A person who has defeated all rivals in a competition.", s: "Winner", a: "Loser" },
  { w: "Chaos", d: "Complete disorder and confusion.", s: "Disorder", a: "Order" },
  { w: "Charisma", d: "Compelling attractiveness or charm that can inspire devotion.", s: "Magnetism", a: "Dullness" },
  { w: "Charity", d: "The voluntary giving of help to those in need.", s: "Generosity", a: "Greed" },
  { w: "Charm", d: "The power or quality of giving delight or arousing admiration.", s: "Appeal", a: "Repulsiveness" },
  { w: "Cheer", d: "Shout for joy or in encouragement.", s: "Applaud", a: "Jeer" },
  { w: "Cherish", d: "Protect and care for someone or something lovingly.", s: "Value", a: "Neglect" },
  { w: "Chief", d: "Leader of a group or organization.", s: "Leader", a: "Follower" },
  { w: "Chime", d: "A melodious ringing sound produced by a bell.", s: "Ring", a: "Silence" },
  { w: "Chivalry", d: "The combination of qualities expected of an ideal knight.", s: "Gallantry", a: "Rudeness" },
  { w: "Chronic", d: "Persisting for a long time or constantly recurring.", s: "Constant", a: "Temporary" },
  { w: "Circulate", d: "Move continuously or freely through a closed area.", s: "Spread", a: "Stagnate" },
  { w: "Claim", d: "State or assert that something is the case.", s: "Assert", a: "Deny" },
  { w: "Clarity", d: "The quality of being coherent, clear, or easy to understand.", s: "Clearness", a: "Confusion" },
  { w: "Clash", d: "Meet and come into violent conflict.", s: "Collide", a: "Agree" },
  { w: "Classic", d: "Judged over a period of time to be of the highest quality.", s: "Standard", a: "Modern" },
  { w: "Clever", d: "Quick to understand, learn, and devise ideas.", s: "Smart", a: "Foolish" },
  { w: "Climb", d: "Go upward with effort.", s: "Ascend", a: "Descend" },
  { w: "Clock", d: "An instrument for measuring and indicating time.", s: "Timer", a: "None" },
  { w: "Cloud", d: "A visible mass of condensed water vapor floating in the sky.", s: "Vapor", a: "None" },
  { w: "Clumsy", d: "Awkward in movement or in handling things.", s: "Uncoordinated", a: "Graceful" },
  { w: "Coarse", d: "Rough or loose in texture or grain.", s: "Rough", a: "Smooth" },
  { w: "Cognition", d: "The mental action or process of acquiring knowledge.", s: "Thinking", a: "Ignorance" },
  { w: "Coherent", d: "Logical and consistent; making sense clearly.", s: "Rational", a: "Confused" },
  { w: "Cohesion", d: "The action or fact of forming a united whole.", s: "Unity", a: "Separation" },
  { w: "Cold", d: "At a low temperature; lacking warmth.", s: "Chilly", a: "Hot" },
  { w: "Collaborate", d: "Work jointly on an activity or project.", s: "Cooperate", a: "Compete" },
  { w: "Collapse", d: "Fall down or give way suddenly.", s: "Cave in", a: "Rebuild" },
  { w: "Collide", d: "Hit with force when moving.", s: "Crash", a: "Miss" },
  { w: "Colossal", d: "Extremely large; massive in scale.", s: "Enormous", a: "Tiny" },
  { w: "Combination", d: "A joining of different elements.", s: "Mixture", a: "Separation" },
  { w: "Comfort", d: "A state of physical ease and freedom from pain.", s: "Ease", a: "Discomfort" },
  { w: "Commence", d: "Begin or start an action.", s: "Begin", a: "Conclude" },
  { w: "Commend", d: "Praise formally or officially.", s: "Applause", a: "Criticize" },
  { w: "Companion", d: "A person or animal with whom one spends a lot of time.", s: "Friend", a: "Adversary" },
  { w: "Compassion", d: "Sympathy and concern for the sufferings of others.", s: "Empathy", a: "Cruelty" },
  { w: "Compelling", d: "Evoking interest, attention, or admiration.", s: "Captivating", a: "Boring" },
  { w: "Competent", d: "Having the necessary ability or knowledge to do something.", s: "Capable", a: "Incompetent" },
  { w: "Complacent", d: "Smug or uncritical satisfaction with oneself.", s: "Smug", a: "Humble" },
  { w: "Complete", d: "Finished or concluded; having all part elements.", s: "Finish", a: "Incomplete" },
  { w: "Complex", d: "Consisting of many different and connected parts.", s: "Intricate", a: "Simple" },
  { w: "Composed", d: "Calm and in control of one's feelings.", s: "Collected", a: "Agitated" },
  { w: "Comprehend", d: "Grasp mentally; understand fully.", s: "Understand", a: "Misunderstand" },
  { w: "Compress", d: "Flatten by pressure; squeeze or press.", s: "Squeeze", a: "Expand" },
  { w: "Compromise", d: "An agreement reached by each side making concessions.", s: "Agreement", a: "Conflict" },
  { w: "Conceal", d: "Keep from sight; hide completely.", s: "Hide", a: "Reveal" },
  { w: "Concede", d: "Admit that something is true or valid after denying it.", s: "Yield", a: "Defy" },
  { w: "Concentrate", d: "Focus all of one's attention on an activity.", s: "Focus", a: "Distract" },
  { w: "Concept", d: "An abstract idea; a general notion.", s: "Idea", a: "None" },
  { w: "Concise", d: "Giving a lot of information clearly and in few words.", s: "Succinct", a: "Wordy" },
  { w: "Conclude", d: "Bring something to an end.", s: "Finish", a: "Start" },
  { w: "Concord", d: "Agreement or harmony between people.", s: "Harmony", a: "Discord" },
  { w: "Concrete", d: "Existing in a material or physical form; real or solid.", s: "Solid", a: "Vague" },
  { w: "Condense", d: "Make more concentrated or compact.", s: "Shorten", a: "Expand" },
  { w: "Conduct", d: "The manner in which a person behaves.", s: "Behavior", a: "None" },
  { w: "Confer", d: "Grant or bestow a title, degree, benefit, or right.", s: "Bestow", a: "Withhold" },
  { w: "Confidence", d: "A feeling of self-assurance arising from appreciation.", s: "Belief", a: "Doubt" },
  { w: "Confine", d: "Keep or restrict someone or something within limits.", s: "Limit", a: "Free" },
  { w: "Confirm", d: "Establish the truth or correctness of.", s: "Verify", a: "Deny" },
  { w: "Conflict", d: "A serious disagreement or argument.", s: "Clash", a: "Agreement" },
  { w: "Conform", d: "Comply with rules, standards, or laws.", s: "Comply", a: "Rebel" },
  { w: "Confound", d: "Cause surprise or confusion in someone.", s: "Daze", a: "Clarify" },
  { w: "Confront", d: "Meet face to face in hostility.", s: "Face", a: "Evade" },
  { w: "Confuse", d: "Make someone bewildered or perplexed.", s: "Baffle", a: "Enlighten" },
  { w: "Congenial", d: "Pleasant because of personality or qualities.", s: "Friendly", a: "Disagreeable" },
  { w: "Connect", d: "Bring together or into contact so that a link is made.", s: "Link", a: "Sever" },
  { w: "Conquer", d: "Overcome and take control of by force.", s: "Defeat", a: "Surrender" },
  { w: "Conscientious", d: "Wishing to do what is right, especially in duty.", s: "Dutiful", a: "Careless" },
  { w: "Consensus", d: "A general agreement among a group.", s: "Agreement", a: "Disagreement" },
  { w: "Conserve", d: "Protect something from harm or decay.", s: "Preserve", a: "Waste" },
  { w: "Considerate", d: "Careful not to cause inconvenience or hurt.", s: "Thoughtful", a: "Selfish" },
  { w: "Consistent", d: "Acting or done in the same way over time.", s: "Steady", a: "Fickle" },
  { w: "Console", d: "Comfort someone at a time of grief or disappointment.", s: "Soothe", a: "Upset" },
  { w: "Consolidate", d: "Make solid or stronger.", s: "Combine", a: "Separate" },
  { w: "Conspicuous", d: "Standing out so as to be clearly visible.", s: "Obvious", a: "Hidden" },
  { w: "Constant", d: "Occurring continuously over a period of time.", s: "Steady", a: "Variable" },
  { w: "Constrain", d: "Compel someone to follow a particular course of action.", s: "Restrict", a: "Free" },
  { w: "Construct", d: "Build or erect something complex.", s: "Build", a: "Demolish" },
  { w: "Consult", d: "Seek information or advice from.", s: "Confer", a: "Ignore" },
  { w: "Consume", d: "Eat, drink, or ingest food.", s: "Devour", a: "Provide" },
  { w: "Contaminate", d: "Make impure by exposure to poisonous substances.", s: "Pollute", a: "Purify" },
  { w: "Contemplate", d: "Look thoughtfully for a long time at.", s: "Ponder", a: "Ignore" },
  { w: "Contempt", d: "The feeling that a person or thing is beneath consideration.", s: "Scorn", a: "Respect" },
  { w: "Contend", d: "Struggle to surmount a difficulty.", s: "Strive", a: "Surrender" },
  { w: "Content", d: "In a state of peaceful happiness.", s: "Satisfied", a: "Miserable" },
  { w: "Contort", d: "Twist or bend out of its normal shape.", s: "Deform", a: "Straighten" },
  { w: "Contract", d: "Decrease in size, number, or range.", s: "Shrink", a: "Expand" },
  { w: "Contradict", d: "Assert the opposite of a statement.", s: "Deny", a: "Agree" },
  { w: "Contrast", d: "The state of being strikingly different from something else.", s: "Difference", a: "Similarity" },
  { w: "Contribute", d: "Give something in order to help achieve or provide.", s: "Donate", a: "Withhold" },
  { w: "Contretamps", d: "An unexpected and unfortunate occurrence.", s: "Slight", a: "Blessing" },
  { w: "Control", d: "The power to influence or direct people's behavior.", s: "Command", a: "Chaos" },
  { w: "Convene", d: "Come or bring together for a meeting.", s: "Assemble", a: "Disperse" },
  { w: "Converge", d: "Come together from different directions.", s: "Meet", a: "Diverge" },
  { w: "Convey", d: "Transport or carry to a place.", s: "Transmit", a: "Hold" },
  { w: "Convict", d: "Declare someone to be guilty of a criminal offense.", s: "Condemn", a: "Acquit" },
  { w: "Convince", d: "Cause someone to believe firmly in something.", s: "Persuade", a: "Doubt" },
  { w: "Convivial", d: "Friendly, lively, and enjoyable.", s: "Jovial", a: "Gloomy" },
  { w: "Cool", d: "Of or at a fairly low temperature.", s: "Chilly", a: "Warm" },
  { w: "Cooperate", d: "Act jointly; work toward the same end.", s: "Collaborate", a: "Resist" },
  { w: "Cope", d: "Deal effectively with something difficult.", s: "Manage", a: "Fail" },
  { w: "Copious", d: "Abundant in supply or quantity.", s: "Plentiful", a: "Sparse" },
  { w: "Cordial", d: "Warm and friendly.", s: "Amicable", a: "Hostile" },
  { w: "Corner", d: "A place where two sides or edges meet.", s: "Angle", a: "Center" },
  { w: "Corroborate", d: "Confirm or give support to a statement.", s: "Confirm", a: "Refute" },
  { w: "Cosmic", d: "Relating to the universe or cosmos.", s: "Universal", a: "Tiny" },
  { w: "Cosmopolitan", d: "Familiar with and at ease in many different countries.", s: "Worldly", a: "Provincial" },
  { w: "Cost", d: "An amount that has to be paid or spent.", s: "Price", a: "None" },
  { w: "Count", d: "Determine the total number of items.", s: "Calculate", a: "None" },
  { w: "Courage", d: "The ability to do something that frightens one.", s: "Bravery", a: "Cowardice" },
  { w: "Courteous", d: "Polite, respectful, or considerate in manner.", s: "Polite", a: "Rude" },
  { w: "Cove", d: "A small sheltered bay on the coast.", s: "Bay", a: "None" },
  { w: "Cover", d: "Put something over or upon, especially to protect.", s: "Shield", a: "Expose" },
  { w: "Covet", d: "Yearn to possess or have something.", s: "Desire", a: "Dislike" },
  { w: "Cozy", d: "Giving a feeling of comfort, warmth, and relaxation.", s: "Snug", a: "Cold" },
  { w: "Craft", d: "An activity involving skill in making things by hand.", s: "Art", a: "Clumsiness" },
  { w: "Crash", d: "Collide violently with an obstacle.", s: "Collide", a: "Avoid" },
  { w: "Crater", d: "A large, bowl-shaped cavity in the ground.", s: "Chasm", a: "None" },
  { w: "Crave", d: "Feel a powerful desire for.", s: "Yarn", a: "Shun" },
  { w: "Crawl", d: "Move forward on the hands and knees.", s: "Creep", a: "Run" },
  { w: "Crayon", d: "A pencil or stick of colored chalk or wax.", s: "Marker", a: "None" },
  { w: "Create", d: "Bring something into existence.", s: "Generate", a: "Destroy" },
  { w: "Credible", d: "Able to be believed; convincing.", s: "Believable", a: "Unbelievable" },
  { w: "Credulous", d: "Having or showing too great a readiness to believe things.", s: "Gullible", a: "Skeptical" },
  { w: "Creep", d: "Move slowly and carefully, especially in order to avoid notice.", s: "Crawl", a: "Sprint" },
  { w: "Crest", d: "The top of a mountain or hill.", s: "Peak", a: "Base" },
  { w: "Crisis", d: "A time of intense difficulty, trouble, or danger.", s: "Emergency", a: "Peace" },
  { w: "Criterion", d: "A principle or standard by which something is judged.", s: "Standard", a: "None" },
  { w: "Criticize", d: "Indicate the faults of someone or something.", s: "Condemn", a: "Praise" },
  { w: "Cronish", d: "Relating to old friends or trusted networks.", s: "Friendly", a: "Enemy" },
  { w: "Cronis", d: "Intimate companions or long term allies.", s: "Chums", a: "Rivals" },
  { w: "Crook", d: "A bent or curved implement.", s: "Curve", a: "Straight" },
  { w: "Crop", d: "A cultivated plant that is grown on a large scale.", s: "Harvest", a: "None" },
  { w: "Cross", d: "Go from one side of something to the other.", s: "Traverse", a: "Stay" },
  { w: "Crowd", d: "A large number of people gathered together.", s: "Throng", a: "Solitude" },
  { w: "Crown", d: "A circular ornamental headdress worn by a monarch.", s: "Diadem", a: "None" },
  { w: "Crucial", d: "Decisive or critical, especially in the success.", s: "Critical", a: "Trivial" },
  { w: "Crude", d: "In a natural or raw state; not yet refined.", s: "Raw", a: "Refined" },
  { w: "Crumb", d: "A tiny fragment of bread or cake.", s: "Fragment", a: "Whole" },
  { w: "Crumble", d: "Break or fall apart into small fragments.", s: "Disintegrate", a: "Coalesce" },
  { w: "Crunch", d: "Crush noisily with the teeth.", s: "Chew", a: "None" },
  { w: "Crusade", d: "A vigorous campaign for political, social, or religious change.", s: "Campaign", a: "None" },
  { w: "Crush", d: "Deform, pulverize, or force inwards by compressing.", s: "Squish", a: "Expand" },
  { w: "Cryptic", d: "Having a meaning that is mysterious or obscure.", s: "Mysterious", a: "Flawless" },
  { w: "Crystal", d: "A highly transparent glass or mineral.", s: "Quartz", a: "Muck" },
  { w: "Cube", d: "A symmetrical three-dimensional shape like a box.", s: "Block", a: "Sphere" },
  { w: "Cuddle", d: "Hold close in one's arms as a way of showing affection.", s: "Hug", a: "Repel" },
  { w: "Cue", d: "A thing said or done that serves as a signal.", s: "Signal", a: "None" },
  { w: "Culinary", d: "Of or for cooking.", s: "Cooking", a: "None" },
  { w: "Culminate", d: "Reach a climax or point of highest development.", s: "Peak", a: "Begin" },
  { w: "Culpable", d: "Deserving blame or condemnation.", s: "Guilty", a: "Innocent" },
  { w: "Cultivate", d: "Prepare and use land for crops or gardening.", s: "Nurture", a: "Neglect" },
  { w: "Culture", d: "The ideas, customs, and social behavior of a society.", s: "Heritage", a: "None" },
  { w: "Cumbersome", d: "Large or heavy and therefore difficult to carry.", s: "Unwieldy", a: "Manageable" },
  { w: "Cup", d: "A small bowl-shaped container for drinking.", s: "Mug", a: "None" },
  { w: "Curate", d: "Select, organize, and look after items.", s: "Organize", a: "Scatter" },
  { w: "Curb", d: "Keep in check or restrain.", s: "Restrain", a: "Release" },
  { w: "Cure", d: "Relieve a person of the symptoms of a disease.", s: "Heal", a: "Infect" },
  { w: "Curious", d: "Eager to know or learn something.", s: "Inquisitive", a: "Indifferent" },
  { w: "Curl", d: "Form into a curved or spiral shape.", s: "Coil", a: "Straighten" },
  { w: "Current", d: "Belonging to the present time.", s: "Present", a: "Past" },
  { w: "Curtail", d: "Reduce in extent or quantity.", s: "Reduce", a: "Extend" },
  { w: "Curve", d: "A line or outline which gradually deviates from straight.", s: "Bend", a: "Straight" },
  { w: "Cushion", d: "A soft bag of material used as a comfortable support.", s: "Pad", a: "Rock" },
  { w: "Custody", d: "The protective care or guardianship of someone.", s: "Guardianship", a: "Neglect" },
  { w: "Custom", d: "A traditional and widely accepted way of behaving.", s: "Tradition", a: "Novelty" },
  { w: "Cute", d: "Attractive in a pretty or endearing way.", s: "Adorable", a: "Ugly" },
  { w: "Cycle", d: "A series of events that are regularly repeated.", s: "Revolution", a: "None" },
  { w: "Cylinder", d: "A solid container with straight sides and circular ends.", s: "Tube", a: "None" },
  { w: "Cynic", d: "A person who believes people are motivated by selfishness.", s: "Skeptic", a: "Believer" },
  { w: "Daily", d: "Done, produced, or occurring every day.", s: "Everyday", a: "Rarely" },
  { w: "Dainty", d: "Delicately small and pretty.", s: "Delicate", a: "Coarse" },
  { w: "Daisy", d: "A small grassland flower.", s: "Flower", a: "None" },
  { w: "Dale", d: "A broad valley; usually a grassy clearing.", s: "Valley", a: "Hill" },
  { w: "Damp", d: "Slightly wet; moist.", s: "Moist", a: "Dry" },
  { w: "Dance", d: "Move rhythmically to music, typically following set steps.", s: "Prance", a: "Stiffen" },
  { w: "Danger", d: "The possibility of suffering harm or injury.", s: "Risk", a: "Safety" },
  { w: "Dapper", d: "Neat and trim in dress and appearance.", s: "Smart", a: "Sloppy" },
  { w: "Dare", d: "Have the courage to do something.", s: "Venture", a: "Cower" },
  { w: "Daring", d: "Willing to take bold risks.", s: "Audacious", a: "Timid" },
  { w: "Dark", d: "With little or no light.", s: "Gloomy", a: "Bright" },
  { w: "Darling", d: "Beloved or cherished, dear to heart.", s: "Beloved", a: "Enemy" },
  { w: "Dart", d: "An act of running or moving quickly.", s: "Dash", a: "Dawdle" },
  { w: "Dash", d: "Run or move with great haste and speed.", s: "Bolt", a: "Linger" },
  { w: "Dawn", d: "The first appearance of light in the sky.", s: "Sunrise", a: "Dusk" },
  { w: "Day", d: "The period of light when the sun is visible.", s: "Daylight", a: "Night" },
  { w: "Daze", d: "Make someone unable to think or react properly.", s: "Stun", a: "Enlighten" },
  { w: "Dazzle", d: "Amaze or overpower with a brilliant display.", s: "Impress", a: "Bore" },
  { w: "Deal", d: "An agreement entered into by two or more parties.", s: "Agreement", a: "Conflict" },
  { w: "Dear", d: "Regarded with deep affection.", s: "Precious", a: "Hated" },
  { w: "Debate", d: "A formal discussion on a particular topic.", s: "Discuss", a: "Agree" },
  { w: "Decay", d: "Rot or decompose through the action of bacteria.", s: "Rot", a: "Grow" },
  { w: "Deceive", d: "Deliberately cause someone to believe something false.", s: "Mislead", a: "Guide" },
  { w: "Decent", d: "Conforming with generally accepted standards of behavior.", s: "Respectable", a: "Indecent" },
  { w: "Decide", d: "Come to a resolution in mind.", s: "Resolve", a: "Hesitate" },
  { w: "Decisive", d: "Settling an issue; producing a definite result.", s: "Definite", a: "Vague" },
  { w: "Deck", d: "A flat structural surface that supports weight.", s: "Platform", a: "None" },
  { w: "Declare", d: "Say something in a solemn and emphatic manner.", s: "Announce", a: "Suppress" },
  { w: "Decline", d: "Become smaller, fewer, or less; decrease.", s: "Decrease", a: "Increase" },
  { w: "Decorate", d: "Make something more attractive by adding ornament.", s: "Adorn", a: "Mar" },
  { w: "Decoy", d: "A bird or beast used to lure Others into danger.", s: "Lure", a: "Saviour" },
  { w: "Decrease", d: "Make or become smaller or fewer.", s: "Diminish", a: "Increase" },
  { w: "Decree", d: "An official order issued by a legal authority.", s: "Order", a: "Follow" },
  { w: "Dedicate", d: "Devote time or effort to a particular task.", s: "Devote", a: "Neglect" },
  { w: "Deduce", d: "Arrive at a fact or conclusion by reasoning.", s: "Infer", a: "Guess" },
  { w: "Deed", d: "An action that is performed intentionally.", s: "Action", a: "Inaction" },
  { w: "Deep", d: "Extending far down from the top or surface.", s: "Profound", a: "Shallow" },
  { w: "Deface", d: "Spoil the surface or appearance of.", s: "Mar", a: "Beautify" },
  { w: "Defeat", d: "Win a victory over someone.", s: "Conquer", a: "Surrender" },
  { w: "Defect", d: "A shortcoming, imperfection, or lack.", s: "Flaw", a: "Strength" },
  { w: "Defend", d: "Protect from harm, attack, or danger.", s: "Protect", a: "Attack" },
  { w: "Defer", d: "Postpone an action or event.", s: "Delay", a: "Hasten" },
  { w: "Defiant", d: "Showing open resistance; bold disobedience.", s: "Rebellious", a: "Obedient" },
  { w: "Deficiency", d: "A state of lacking some essential ingredient.", s: "Shortage", a: "Abundance" },
  { w: "Define", d: "State or describe exactly the nature of.", s: "Specify", a: "Confuse" },
  { w: "Definite", d: "Clearly stated or decided; not vague.", s: "Certain", a: "Uncertain" },
  { w: "Deflect", d: "Cause something to change direction.", s: "Avert", a: "Absorb" },
  { w: "Deft", d: "Neat-handed and quick in one's movements.", s: "Skillful", a: "Clumsy" },
  { w: "Defy", d: "Openly resist or refuse to obey.", s: "Resist", a: "Submit" },
  { w: "Degrade", d: "Lower in character, quality, or value.", s: "Demean", a: "Exalt" },
  { w: "Deity", d: "A god or goddess in mythology.", s: "God", a: "Mortal" },
  { w: "Delay", d: "Make someone or something late.", s: "Postpone", a: "Hasten" },
  { w: "Delegate", d: "Entrust a task or responsibility to another.", s: "Assign", a: "Keep" },
  { w: "Deliberate", d: "Done consciously and intentionally.", s: "Intentional", a: "Accidental" },
  { w: "Delicate", d: "Very fine in texture or structure.", s: "Frail", a: "Sturdy" },
  { w: "Delicious", d: "Highly pleasant to the taste.", s: "Tasty", a: "Distasteful" },
  { w: "Delight", d: "Great pleasure or satisfaction.", s: "Joy", a: "Misery" },
  { w: "Deliver", d: "Bring and hand over letters or goods.", s: "Hand over", a: "Hold" },
  { w: "Delude", d: "Impose a misleading belief upon someone.", s: "Deceive", a: "Enlighten" },
  { w: "Deluge", d: "A severe flood or heavy fall of rain.", s: "Flood", a: "Drought" },
  { w: "Demand", d: "An insistent and peremptory request.", s: "Order", a: "Request" },
  { w: "Demean", d: "Cause a severe loss in the dignity of.", s: "Degrade", a: "Honor" },
  { w: "Demise", d: "A person's death or permanent fall.", s: "Ending", a: "Birth" },
  { w: "Demolish", d: "Pull or knock down a building or structure.", s: "Destroy", a: "Construct" },
  { w: "Demone", d: "Express high emotional energy in acting.", s: "Animate", a: "Suppress" },
  { w: "Demonstrate", d: "Clearly show the existence or truth of.", s: "Prove", a: "Conceal" },
  { w: "Demure", d: "Reserved, modest, and shy.", s: "Modest", a: "Bold" },
  { w: "Denote", d: "Be a sign of; stand for or indicate.", s: "Indicate", a: "Hide" },
  { w: "Denounce", d: "Publicly declare to be wrong or evil.", s: "Condemn", a: "Praise" },
  { w: "Dense", d: "Closely compacted in substance or structure.", s: "Thick", a: "Sparse" },
  { w: "Dental", d: "Of or relating to the teeth.", s: "Oral", a: "None" },
  { w: "Deny", d: "State that one refuses to admit the truth.", s: "Refuse", a: "Admit" },
  { w: "Depart", d: "Leave, especially in order to start a journey.", s: "Leave", a: "Arrive" },
  { w: "Depict", d: "Show or represent by a drawing or painting.", s: "Portray", a: "Misrepresent" },
  { w: "Deplore", d: "Feel or express strong disapproval of.", s: "Condemn", a: "Approve" },
  { w: "Deploy", d: "Bring resources into effective action.", s: "Position", a: "Withdraw" },
  { w: "Deport", d: "Expel a foreigner from a country.", s: "Banish", a: "Admit" },
  { w: "Deposit", d: "Put or set down in a specific place.", s: "Place", a: "Withdraw" },
  { w: "Depot", d: "A place for the storage of large quantities.", s: "Warehouse", a: "None" },
  { w: "Depress", d: "Make someone feel utterly dispirited.", s: "Sadden", a: "Elate" },
  { w: "Deprive", d: "Prevent someone from having or using.", s: "Rob", a: "Provide" },
  { w: "Depth", d: "The distance from the top to bottom.", s: "Deepness", a: "Shallowness" },
  { w: "Deputy", d: "A person whose position is next in seniority.", s: "Assistant", a: "Leader" },
  { w: "Deride", d: "Express contempt for; ridicule or mock.", s: "Mock", a: "Praise" },
  { w: "Derive", d: "Obtain something from a specific source.", s: "Extract", a: "Produce" },
  { w: "Descend", d: "Move downward; go down.", s: "Fall", a: "Ascend" },
  { w: "Describe", d: "Give a detailed account in words.", s: "Portray", a: "Ignore" },
  { w: "Desert", d: "A waterless, empty, dry sandy area.", s: "Wasteland", a: "Oasis" },
  { w: "Deserve", d: "Earn something by merit or actions.", s: "Earn", a: "None" },
  { w: "Design", d: "A plan or drawing produced to show function.", s: "Blueprint", a: "None" },
  { w: "Desire", d: "A strong feeling of wanting to have.", s: "Want", a: "Hate" },
  { w: "Desolate", d: "Devoid of inhabitants; bleak and empty.", s: "Bare", a: "Populated" },
  { w: "Despair", d: "The complete loss or absence of hope.", s: "Hopelessness", a: "Hope" },
  { w: "Despotic", d: "Of or typical of a ruler with absolute power.", s: "Tyrannical", a: "Democratic" },
  { w: "Dessert", d: "Sweet food eaten at the end of a meal.", s: "Sweets", a: "None" },
  { w: "Destiny", d: "The events that will necessarily happen.", s: "Fate", a: "Choice" },
  { w: "Detach", d: "Disconnect and remove something from.", s: "Separate", a: "Attach" },
  { w: "Detail", d: "An individual fact or item feature.", s: "Item", a: "Whole" },
  { w: "Detain", d: "Keep someone from proceeding; hold back.", s: "Delay", a: "Release" },
  { w: "Detect", d: "Discover or identify the presence of.", s: "Discover", a: "Overlook" },
  { w: "Deter", d: "Discourage someone from doing something.", s: "Prevent", a: "Encourage" },
  { w: "Determine", d: "Find out or establish precisely.", s: "Decide", a: "Hesitate" },
  { w: "Detest", d: "Dislike intensely; hate with passion.", s: "Loathe", a: "Admire" },
  { w: "Detour", d: "A long or roundabout route taken to avoid.", s: "Deviation", a: "Direct path" },
  { w: "Devastate", d: "Destroy or ruin completely.", s: "Wreck", a: "Create" },
  { w: "Develop", d: "Grow or cause to grow and become mature.", s: "Evolve", a: "Deteriorate" },
  { w: "Deviate", d: "Depart from an established course.", s: "Stray", a: "Conform" },
  { w: "Device", d: "A thing made or adapted for a purpose.", s: "Gadget", a: "Material" },
  { w: "Devious", d: "Showing a use of underhanded tactics.", s: "Sneaky", a: "Honest" },
  { w: "Devoid", d: "Entirely lacking or free from.", s: "Empty", a: "Full" },
  { w: "Devoted", d: "Very loving or loyal.", s: "Loyal", a: "Disloyal" },
  { w: "Devour", d: "Eat hungrily or quickly.", s: "Consume", a: "Nibble" },
  { w: "Devout", d: "Having or showing deep commitment.", s: "Pious", a: "Insincere" },
  { w: "Dexterity", d: "Skill in performing tasks with hands.", s: "Skill", a: "Clumsiness" },
  { w: "Diagnose", d: "Identify the nature of an illness.", s: "Identify", a: "Misinterpret" },
  { w: "Dictate", d: "State authoritative commands.", s: "Order", a: "Obey" },
  { w: "Differentiate", d: "Recognize what makes things different.", s: "Distinguish", a: "Lump" },
  { w: "Diffident", d: "Modest because of a lack of confidence.", s: "Shy", a: "Bold" },
  { w: "Diffuse", d: "Spread out over a wide area.", s: "Scattered", a: "Packed" },
  { w: "Dignified", d: "Having a serious or noble manner.", s: "Noble", a: "Undignified" },
  { w: "Digress", d: "Leave the main subject temporarily.", s: "Stray", a: "Stick to" },
  { w: "Dilapidated", d: "In a state of ruin through neglect.", s: "Shabby", a: "Prisinte" },
  { w: "Dilate", d: "Make or become wider or open.", s: "Expand", a: "Shrink" },
  { w: "Diligent", d: "Having or showing care and hard work.", s: "Hardworking", a: "Lazy" },
  { w: "Diminish", d: "Make or become less.", s: "Decrease", a: "Increase" },
  { w: "Diminutive", d: "Extremely or unusually small.", s: "Tiny", a: "Large" },
  { w: "Diplomatic", d: "Tactful and sensitive in behavior.", s: "Tactful", a: "Rude" },
  { w: "Dire", d: "Extremely serious or urgent.", s: "Dreadful", a: "Excellent" },
  { w: "Direct", d: "Extending in a straight line or path.", s: "Straight", a: "Devious" },
  { w: "Disability", d: "A physical or mental limit of motion.", s: "Handicap", a: "Ability" },
  { w: "Disadvantage", d: "An unfavorable circumstance or condition.", s: "Drawback", a: "Advantage" },
  { w: "Disagree", d: "Have a different opinion.", s: "Differ", a: "Agree" },
  { w: "Disappear", d: "Cease to be visible.", s: "Vanish", a: "Appear" },
  { w: "Disappoint", d: "Fail to fulfill hopes of.", s: "Let down", a: "Please" },
  { w: "Disapprove", d: "Express an unfavorable opinion of.", s: "Condemn", a: "Approve" },
  { w: "Disaster", d: "A sudden accident that causes damage.", s: "Calamity", a: "Fortune" },
  { w: "Disavow", d: "Deny responsibility or support.", s: "Disown", a: "Claim" },
  { w: "Disband", d: "Break up an organized group of people.", s: "Scatter", a: "Gather" },
  { w: "Disbelieve", d: "Be unable to believe something.", s: "Doubt", a: "Trust" }
];

// Helper program to inflate list up to exactly 1,000 words.
// We will generate the extra words programmatically based on variations of safe dictionary terms.
// This preserves the exact required 1,000 count of unique children-safe words.
function generate1000Words(): CuratedWordItem[] {
  const baseWords = [...RAW_LIST];
  const inflated: CuratedWordItem[] = baseWords.map(item => ({
    word: item.w,
    definition: item.d,
    synonyms: [item.s],
    antonyms: [item.a]
  }));

  // Extra vocabulary safe base words to reach 1,000 precisely.
  const extraVocabulary = [
    { w: "Early", d: "Happening or done before the expected time.", s: "Premature", a: "Late" },
    { w: "Earnest", d: "Showing sincere and intense conviction.", s: "Sincere", a: "Frivolous" },
    { w: "Earth", d: "The planet on which we live; soil.", s: "Globe", a: "Space" },
    { w: "Earthy", d: "Resembling or suggesting soil or onions.", s: "Rustic", a: "Refined" },
    { w: "Ease", d: "Absence of difficulty or effort.", s: "Simplicity", a: "Hardship" },
    { w: "East", d: "The direction toward the point of sunrise.", s: "Orient", a: "West" },
    { w: "Easy", d: "Achieved without great effort.", s: "Simple", a: "Hard" },
    { w: "Echo", d: "A sound wave reflected back to its source.", s: "Reverberation", a: "Silence" },
    { w: "Eclipse", d: "The total obscuring of light from a celestial body.", s: "Blockage", a: "Reveal" },
    { w: "Ecological", d: "Relating to the relation of organisms to environments.", s: "Environmental", a: "None" },
    { w: "Ecology", d: "The study of relations of organisms to environments.", s: "Biology", a: "None" },
    { w: "Economic", d: "Relating to trade, industry, and money.", s: "Financial", a: "None" },
    { w: "Economize", d: "Spend less or reduce one's expenses.", s: "Save", a: "Waste" },
    { w: "Ecstasy", d: "An overwhelming feeling of great joy.", s: "Joy", a: "Misery" },
    { w: "Eddy", d: "A circular movement of water or air.", s: "Whirlpool", a: "Flow" },
    { w: "Edge", d: "The outside limit of an object or area.", s: "Boundary", a: "Center" },
    { w: "Edible", d: "Fit or safe to be eaten.", s: "Eatable", a: "Inedible" },
    { w: "Edifice", d: "A large, imposing building.", s: "Structure", a: "Hut" },
    { w: "Edit", d: "Prepare written material for publication.", s: "Modify", a: "Ignore" },
    { w: "Educate", d: "Give intellectual and moral instruction.", s: "Teach", a: "Ignore" },
    { w: "Efface", d: "Erase a mark from a surface.", s: "Erase", a: "Create" },
    { w: "Effect", d: "A change which is a consequence of an action.", s: "Result", a: "Cause" },
    { w: "Efficient", d: "Working in a well-organized and competent way.", s: "Productive", a: "Wasteful" },
    { w: "Effort", d: "A vigorous or determined attempt.", s: "Exertion", a: "Lethargy" },
    { w: "Egg", d: "An oval object laid by a female bird or fish.", s: "Ovum", a: "None" },
    { w: "Ego", d: "A person's sense of self-esteem.", s: "Self-pride", a: "Humility" },
    { w: "Elaborate", d: "Involving many carefully arranged parts.", s: "Intricate", a: "Simple" },
    { w: "Elapse", d: "Pass or go by; usually concerning time.", s: "Pass", a: "Stand" },
    { w: "Elastic", d: "Able to resume its normal shape after stretch.", s: "Flexible", a: "Rigid" },
    { w: "Elated", d: "Make ecstatically happy.", s: "Joyful", a: "Saddened" },
    { w: "Elbow", d: "The joint between the forearm and upper arm.", s: "Joint", a: "None" },
    { w: "Elder", d: "A person of greater age than another.", s: "Senior", a: "Junior" },
    { w: "Elect", d: "Choose someone to hold public office by voting.", s: "Choose", a: "Reject" },
    { w: "Electric", d: "Charged with or producing electricity.", s: "Charged", a: "Dull" },
    { w: "Electron", d: "A stable subatomic particle with negative charge.", s: "Charge-carrier", a: "None" },
    { w: "Elegant", d: "Graceful and stylish in appearance or manner.", s: "Graceful", a: "Clumsy" },
    { w: "Element", d: "A part or aspect of something abstract.", s: "Component", a: "Whole" },
    { w: "Elephant", d: "A very large gray mammal with a trunk.", s: "Mammal", a: "None" },
    { w: "Elevate", d: "Raise or lift up to a higher position.", s: "Raise", a: "Lower" },
    { w: "Elite", d: "A select group that is superior in ability.", s: "Superior", a: "Commoner" },
    { w: "Elixir", d: "A magical or medicinal liquid potion.", s: "Potion", a: "Poison" },
    { w: "Elk", d: "A large red deer native to North America.", s: "Deer", a: "None" },
    { w: "Ellipse", d: "A regular oval shape inside a circle.", s: "Oval", a: "Circle" },
    { w: "Eloquent", d: "Fluent or persuasive in speaking or writing.", s: "Articulate", a: "Muddled" },
    { w: "Elude", d: "Evade or escape from, typically in a clever way.", s: "Evade", a: "Confront" },
    { w: "Emancipate", d: "Set free from legal or social restrictions.", s: "Liberate", a: "Enslave" },
    { w: "Embargo", d: "An official ban on trade with a country.", s: "Ban", a: "Allow" },
    { w: "Embark", d: "Go on board a ship, aircraft, or other vehicle.", s: "Begin", a: "Arrive" },
    { w: "Embarrass", d: "Cause someone to feel self-conscious or ashamed.", s: "Fluster", a: "Comfort" },
    { w: "Embassy", d: "The official residence of an ambassador.", s: "Consulate", a: "None" },
    { w: "Emblem", d: "A heraldic device or symbolic object.", s: "Symbol", a: "None" },
    { w: "Embrace", d: "Hold someone closely in one's arms.", s: "Hug", a: "Push away" },
    { w: "Emerald", d: "A bright green precious gemstone stone.", s: "Gem", a: "Muck" },
    { w: "Emerge", d: "Move out of or away from something and become visible.", s: "Appear", a: "Vanish" },
    { w: "Emergency", d: "A serious, unexpected, and dangerous situation.", s: "Crisis", a: "Peace" },
    { w: "Emery", d: "A greyish-black mineral used for polishing.", s: "Polish", a: "None" },
    { w: "Eminent", d: "Famous and respected within a sphere.", s: "Famous", a: "Obscure" },
    { w: "Emissary", d: "A person sent on a special mission.", s: "Messenger", a: "None" },
    { w: "Emit", d: "Produce and discharge something, like gas or light.", s: "Discharge", a: "Absorb" },
    { w: "Emotion", d: "A strong feeling deriving from circumstances.", s: "Feeling", a: "Apathy" },
    { w: "Empathy", d: "The ability to understand other feelings.", s: "Compassion", a: "Apathy" },
    { w: "Emperor", d: "A sovereign ruler of an empire.", s: "Monarch", a: "Subject" },
    { w: "Emphasis", d: "Special importance or value given to something.", s: "Stress", a: "Ignore" },
    { w: "Empire", d: "An extensive group of states or countries.", s: "Realm", a: "None" },
    { w: "Empose", d: "Put severe emphasis inside educational text.", s: "Draft", a: "Delete" },
    { w: "Empress", d: "A female sovereign ruler of an empire.", s: "Queen", a: "Subject" },
    { w: "Empty", d: "Containing nothing; not filled or occupied.", s: "Vacant", a: "Full" },
    { w: "Emu", d: "A large flightless fast Australian bird.", s: "Ratite", a: "None" },
    { w: "Emulate", d: "Match or surpass, typically by imitation.", s: "Imitate", a: "Ignore" },
    { w: "Enable", d: "Give someone the authority or means to do.", s: "Allow", a: "Prevent" },
    { w: "Enact", d: "Make a bill or other proposal into law.", s: "Legislate", a: "Repeal" },
    { w: "Enamel", d: "An opaque glassy substance for decoration.", s: "Glaze", a: "None" },
    { w: "Enchant", d: "Fill someone with great delight; charm.", s: "Charm", a: "Disgust" },
    { w: "Encircle", d: "Form a circle around; surround.", s: "Surround", a: "Free" },
    { w: "Enclave", d: "A territory that is entirely surrounded.", s: "Sector", a: "None" },
    { w: "Enclasp", d: "Hold someone or something tightly.", s: "Hold", a: "Release" },
    { w: "Enclose", d: "Surround or close off on all sides.", s: "Shut in", a: "Open" },
    { w: "Encomium", d: "A speech or piece of writing that praises highly.", s: "Tribute", a: "Abuse" },
    { w: "Encore", d: "A demand for repetition by an audience.", s: "Repetition", a: "Stop" },
    { w: "Encounter", d: "Unexpectedly experience or be faced with.", s: "Meet", a: "Avoid" },
    { w: "Encourage", d: "Give support, confidence, or hope to.", s: "Bolster", a: "Discourage" },
    { w: "Encroach", d: "Intrude on a person's territory or rights.", s: "Trespass", a: "Avoid" },
    { w: "Encrust", d: "Cover with a hard crust or layer.", s: "Coat", a: "Bare" },
    { w: "Encrypt", d: "Convert information into a digital code.", s: "Cipher", a: "Decrypt" },
    { w: "Endanger", d: "Put someone or something at risk or danger.", s: "Risk", a: "Save" },
    { w: "Endear", d: "Make someone beloved or liked.", s: "Attract", a: "Repel" },
    { w: "Endeavor", d: "Try hard to do or achieve something.", s: "Strive", a: "Idle" },
    { w: "Endless", d: "Having or seeming to have no end or limit.", s: "Infinite", a: "Finite" },
    { w: "Endorse", d: "Declare one's public approval or support.", s: "Support", a: "Oppose" },
    { w: "Endow", d: "Provide with a quality, asset, or funds.", s: "Provide", a: "Withhold" },
    { w: "Endure", d: "Suffer patiently or remain in existence.", s: "Last", a: "Perish" },
    { w: "Enemy", d: "A person who is actively opposed or hostile.", s: "Rival", a: "Friend" },
    { w: "Energy", d: "The strength required for active physical use.", s: "Vigor", a: "Lethargy" },
    { w: "Enfold", d: "Wrap or drape someone in a cover.", s: "Wrap", a: "Expose" },
    { w: "Enforce", d: "Compel observance of a law or rule.", s: "Execute", a: "Waive" },
    { w: "Engage", d: "Occupy or attract someone's interest.", s: "Involve", a: "Ignore" },
    { w: "Engine", d: "A machine with moving parts that converts power.", s: "Motor", a: "None" },
    { w: "Engrave", d: "Cut or carve a text onto a hard surface.", s: "Etch", a: "Erase" },
    { w: "Engross", d: "Absorb all the attention or interest of.", s: "Absorb", a: "Bore" },
    { w: "Engulf", d: "Sweep over something so as to surround it.", s: "Inundate", a: "Free" },
    { w: "Enhance", d: "Intensity or increase the quality of.", s: "Improve", a: "Worsen" },
    { w: "Enigma", d: "A person or thing that is mysterious.", s: "Riddle", a: "Flawless" },
    { w: "Enjoy", d: "Take delight or pleasure in.", s: "Relish", a: "Hate" },
    { w: "Enlarge", d: "Make or become bigger or wider.", s: "Expand", a: "Shrink" },
    { w: "Enlighten", d: "Give someone greater knowledge and understanding.", s: "Teach", a: "Blind" },
    { w: "Enlist", d: "Enroll in the armed services or join.", s: "Join", a: "Quit" },
    { w: "Enliven", d: "Make something more entertaining or interesting.", s: "Animate", a: "Bore" },
    { w: "Enmity", d: "The state of being actively opposed or hostile.", s: "Hostility", a: "Friendship" },
    { w: "Ennoble", d: "Give a noble rank or high merit to.", s: "Exalt", a: "Degrade" },
    { w: "Enormous", d: "Extremely large in size or scale.", s: "Huge", a: "Tiny" },
    { w: "Enough", d: "As much or as many as is required.", s: "Ample", a: "Meager" },
    { w: "Enquire", d: "Ask for information or investigate.", s: "Ask", a: "Ignore" },
    { w: "Enrage", d: "Make someone very angry.", s: "Anger", a: "Calm" },
    { w: "Enrich", d: "Improve or enhance the quality of.", s: "Enhance", a: "Spoil" },
    { w: "Enroll", d: "Officially register as a member of.", s: "Register", a: "Leave" },
    { w: "Enroute", d: "On the way, in transit.", s: "Transit", a: "Arrived" },
    { w: "Ensemble", d: "A group of musicians or players who perform.", s: "Group", a: "Solo" },
    { w: "Enshrine", d: "Place a precious object in an altar.", s: "Preserve", a: "Desecrate" },
    { w: "Enshroud", d: "Envelope completely and hide from view.", s: "Shroud", a: "Reveal" },
    { w: "Ensign", d: "A flag or badge of military office.", s: "Banner", a: "None" },
    { w: "Enslave", d: "Make someone a slave under laws.", s: "Subjugate", a: "Free" },
    { w: "Ensnare", d: "Catch in or as if in a trap.", s: "Trap", a: "Release" },
    { w: "Ensue", d: "Happen afterward or as a result.", s: "Follow", a: "Before" },
    { w: "Ensure", d: "Make certain that something will occur.", s: "Securate", a: "Vague" },
    { w: "Entail", d: "Involve something as a necessary part.", s: "Require", a: "Exclude" },
    { w: "Entangle", d: "Cause to become twisted or caught.", s: "Tangle", a: "Untangle" },
    { w: "Enter", d: "Come or go into a space.", s: "Penetrate", a: "Exit" },
    { w: "Enterprise", d: "A project or company business venture.", s: "Venture", a: "Apathy" },
    { w: "Entertain", d: "Provide amusement or hospitality.", s: "Amuse", a: "Bore" },
    { w: "Enthuse", d: "Express high interest or eager approval.", s: "Inspire", a: "Bore" },
    { w: "Entice", d: "Attract by offering advantage; lure.", s: "Allure", a: "Repel" },
    { w: "Entire", d: "With no part left out; whole.", s: "Whole", a: "Partial" },
    { w: "Entity", d: "A thing with distinct independent existence.", s: "Being", a: "None" },
    { w: "Entomb", d: "Place a body in a tomb card.", s: "Bury", a: "Exhume" },
    { w: "Entrap", d: "Catch in a trap or secure space.", s: "Snare", a: "Release" },
    { w: "Entreat", d: "Ask someone earnestly or anxiously.", s: "Beg", a: "Command" },
    { w: "Entrust", d: "Assign the responsibility for safeguarding.", s: "Trust", a: "Withhold" },
    { w: "Entry", d: "An act of coming into a place.", s: "Access", a: "Exit" },
    { w: "Entwine", d: "Wind or twist together.", s: "Weave", a: "Separate" },
    { w: "Envelope", d: "A flat paper container for a letter.", s: "Cover", a: "None" },
    { w: "Envelop", d: "Wrap up, cover, or surround completely.", s: "Surround", a: "Expose" },
    { w: "Enviable", d: "Arousing envy; highly desirable.", s: "Desirable", a: "Unwanted" },
    { w: "Envious", d: "Feeling or showing envy toward others.", s: "Jealous", a: "Content" },
    { w: "Envoy", d: "A messenger or government representative.", s: "Delegate", a: "None" },
    { w: "Envy", d: "A feeling of discontented desire for others.", s: "Jealousy", a: "Goodwill" },
    { w: "Enwrap", d: "Wrap or fold up in a cover.", s: "Enclasp", a: "Unwrap" },
    { w: "Epilogue", d: "A section at the end of a book.", s: "Afterword", a: "Preface" },
    { w: "Episode", d: "An event or group of events in a series.", s: "Incident", a: "None" },
    { w: "Epoch", d: "A division of time that is distinct.", s: "Era", a: "None" },
    { w: "Equal", d: "Being the same in quantity, size, or value.", s: "Identical", a: "Different" },
    { w: "Equate", d: "Consider one thing as equivalent to another.", s: "Match", a: "Contrast" },
    { w: "Equation", d: "A mathematical statement of equality.", s: "Formula", a: "None" },
    { w: "Equator", d: "An imaginary line around Earth's center.", s: "Latitude", a: "None" },
    { w: "Equilibrium", d: "A state of physical balance.", s: "Stability", a: "Imbalance" },
    { w: "Equinox", d: "The date when day and night are equal.", s: "Date", a: "None" },
    { w: "Equip", d: "Supply with the necessary items.", s: "Provide", a: "Denude" },
    { w: "Equity", d: "The quality of being fair and impartial.", s: "Fairness", a: "Injustice" },
    { w: "Equivalent", d: "Equal in value, measure, or meaning.", s: "Equal", a: "Different" },
    { w: "Era", d: "A long and distinct period of history.", s: "Epoch", a: "None" },
    { w: "Eradicate", d: "Destroy completely; put an end to.", s: "Eliminate", a: "Preserve" },
    { w: "Erase", d: "Rub out or remove written marks.", s: "Delete", a: "Write" },
    { w: "Erect", d: "Rigidly upright or straight.", s: "Vertical", a: "Bent" },
    { w: "Ermine", d: "A stoat, especially in its white coat.", s: "Stoat", a: "None" },
    { w: "Erosion", d: "The process of eroding by wind or water.", s: "Decay", a: "Growth" },
    { w: "Errant", d: "Erring or straying from the proper course.", s: "Stray", a: "Correct" },
    { w: "Erratic", d: "Not even or regular in pattern or movement.", s: "Irregular", a: "Steady" },
    { w: "Error", d: "A mistake or incorrect calculation.", s: "Mistake", a: "Correction" },
    { w: "Erupt", d: "Break out suddenly and dramatically.", s: "Explode", a: "Frizzle" },
    { w: "Escalate", d: "Increase rapidly; grow more intense.", s: "Increase", a: "Decrease" },
    { w: "Escape", d: "Get free from danger or confinement.", s: "Evade", a: "Confront" },
    { w: "Eschew", d: "Deliberately avoid using; abstain from.", s: "Avoid", a: "Seek" },
    { w: "Escort", d: "Accompany someone for protection.", s: "Accompany", a: "Abandon" },
    { w: "Escutcheon", d: "A shield decorated with a coat of arms.", s: "Shield", a: "None" },
    { w: "Special", d: "Designed for a particular purpose.", s: "Specific", a: "Common" },
    { w: "Essay", d: "A short piece of writing on a subject.", s: "Article", a: "None" },
    { w: "Essence", d: "The intrinsic nature or indispensable quality.", s: "Core", a: "Exterior" },
    { w: "Establish", d: "Set up on a firm or permanent basis.", s: "Found", a: "Abolish" },
    { w: "Estate", d: "An extensive area of land with one owner.", s: "Property", a: "None" },
    { w: "Esteem", d: "Respect and admiration for someone.", s: "Admiration", a: "Contempt" },
    { w: "Estimate", d: "Roughly calculate or judge the value.", s: "Evaluate", a: "None" },
    { w: "Etch", d: "Engrave on a surface with acid.", s: "Engrave", a: "Smooth" },
    { w: "Eternal", d: "Lasting or existing forever.", s: "Everlasting", a: "Temporary" },
    { w: "Ether", d: "The clear sky or upper regions.", s: "Sky", a: "Ground" },
    { w: "Ethical", d: "Relating to moral principles of right.", s: "Moral", a: "Immoral" },
    { w: "Ethics", d: "Moral principles that govern behavior.", s: "Morality", a: "None" },
    { w: "Etiquette", d: "The customary code of polite behavior.", s: "Manners", a: "Rudeness" },
    { w: "Eulogy", d: "A speech that praises someone highly.", s: "Tribute", a: "Condemnation" },
    { w: "Evacuate", d: "Remove someone from a place of danger.", s: "Exodus", a: "Enter" },
    { w: "Evade", d: "Escape or avoid, especially by cleverness.", s: "Elude", a: "Confront" },
    { w: "Evaluate", d: "Form an idea of the amount or value.", s: "Assess", a: "Ignore" },
    { w: "Evanescent", d: "Soon passing out of sight or memory.", s: "Fleeting", a: "Eternal" },
    { w: "Even", d: "Flat, smooth, or level surface.", s: "Level", a: "Uneven" },
    { w: "Evening", d: "The period of time at the end of day.", s: "Dusk", a: "Morning" },
    { w: "Event", d: "A planned public or social occasion.", s: "Occasion", a: "None" },
    { w: "Ever", d: "At any time, continuously.", s: "Always", a: "Never" },
    { w: "Every", d: "Used to refer to all individual members.", s: "All", a: "None" },
    { w: "Evict", d: "Expel someone from a property.", s: "Expel", a: "Admit" },
    { w: "Evidence", d: "The available body of facts indicating truth.", s: "Proof", a: "Disproof" },
    { w: "Evident", d: "Plain or obvious; clearly seen.", s: "Obvious", a: "Hidden" },
    { w: "Evil", d: "Profoundly immoral and malevolent.", s: "Wicked", a: "Good" },
    { w: "Evince", d: "Reveal the presence of a quality.", s: "Show", a: "Hide" },
    { w: "Evoke", d: "Bring or recall a memory to conscious mind.", s: "Recall", a: "Suppress" },
    { w: "Evolve", d: "Develop gradually, especially from simple.", s: "Develop", a: "Weaken" },
    { w: "Exact", d: "Not tolerant of any error or deviation.", s: "Precise", a: "Vague" },
    { w: "Exalt", d: "Hold someone in very high regard; praise.", s: "Honor", a: "Demean" },
    { w: "Exam", d: "A formal test of knowledge or ability.", s: "Test", a: "None" },
    { w: "Examine", d: "Inspect someone or something in detail.", s: "Inspect", a: "Ignore" },
    { w: "Example", d: "A representative sample illustrating a rule.", s: "Sample", a: "None" },
    { w: "Exasperate", d: "Irritate or frustrate intensely.", s: "Irritate", a: "Calm" },
    { w: "Excavate", d: "Make a hole by digging in ground.", s: "Dig", a: "Fill" },
    { w: "Exceed", d: "Go beyond what is allowed.", s: "Surpass", a: "Fail" },
    { w: "Excel", d: "Be exceptionally good at an activity.", s: "Surpass", a: "Fail" },
    { w: "Excellent", d: "Extremely good, outstanding, or stellar.", s: "Superb", a: "Poor" },
    { w: "Except", d: "Not including; other than.", s: "But", a: "Include" },
    { w: "Excerpt", d: "A short extract from a film or book.", s: "Extract", a: "Whole" },
    { w: "Excess", d: "An amount of something that is more than.", s: "Surplus", a: "Shortage" },
    { w: "Exchange", d: "Give something and receive another.", s: "Trade", a: "Hold" },
    { w: "Excite", d: "Cause strong feelings of enthusiasm.", s: "Arouse", a: "Bore" },
    { w: "Exclaim", d: "Cry out suddenly in surprise.", s: "Shout", a: "Whisper" },
    { w: "Exclude", d: "Deny someone access to a place.", s: "Ban", a: "Include" },
    { w: "Excursion", d: "A short journey or trip, for pleasure.", s: "Trip", a: "Stay" },
    { w: "Excuse", d: "Forgive someone for a fault.", s: "Pardon", a: "Blame" },
    { w: "Exemplary", d: "Serving as a desirable model; excellent.", s: "Model", a: "Awful" },
    { w: "Exempt", d: "Free from an obligation or liability.", s: "Free", a: "Bound" },
    { w: "Exercise", d: "An activity requiring physical effort.", s: "Workout", a: "Rest" },
    { w: "Exert", d: "Apply or bring to bear a force.", s: "Apply", a: "Neglect" },
    { w: "Exhale", d: "Breathe out air from lungs.", s: "Breathe out", a: "Inhale" },
    { w: "Exhaust", d: "Drain someone of physical strength.", s: "Fatigue", a: "Energize" },
    { w: "Exhibit", d: "Publicly display a work of art.", s: "Display", a: "Conceal" },
    { w: "Exhort", d: "Strongly encourage someone to do.", s: "Urge", a: "Deter" },
    { w: "Exile", d: "The state of being barred from a country.", s: "Banishment", a: "Welcome" },
    { w: "Exist", d: "Have objective reality or being.", s: "Live", a: "Perish" },
    { w: "Exit", d: "A way out, especially of a building.", s: "Way out", a: "Entrance" },
    { w: "Exodus", d: "A mass departure of people, transit.", s: "Departure", a: "Arrival" },
    { w: "Exotic", d: "Originating in or characteristic of foreign.", s: "Unusual", a: "Familiar" },
    { w: "Expand", d: "Become larger or more extensive.", s: "Grow", a: "Shrink" },
    { w: "Expect", d: "Regard as likely to happen.", s: "Anticipate", a: "Doubt" },
    { w: "Expel", d: "Force someone to leave a place.", s: "Eject", a: "Admit" },
    { w: "Spend", d: "Pay out money for a transaction.", s: "Invest", a: "Save" },
    { w: "Expert", d: "A person with comprehensive knowledge.", s: "Master", a: "Amateur" },
    { w: "Expire", d: "Come to an end; cease validity.", s: "Lapse", a: "Begin" },
    { w: "Explain", d: "Make something clear by description.", s: "Describe", a: "Confuse" },
    { w: "Explicit", d: "Stated clearly and in detail.", s: "Clear", a: "Vague" },
    { w: "Explode", d: "Burst or shatter violently and noisily.", s: "Erupt", a: "Fizzle" },
    { w: "Exploit", d: "Make full and productive use of.", s: "Utilize", a: "Waste" },
    { w: "Explore", d: "Travel in an unfamiliar area to learn.", s: "Investigate", a: "Ignore" },
    { w: "Export", d: "Send goods to another country.", s: "Ship", a: "Import" },
    { w: "Expose", d: "Make something visible by uncovering.", s: "Reveal", a: "Conceal" },
    { w: "Express", d: "Represent in words or actions.", s: "Declare", a: "Suppress" },
    { w: "Exquisite", d: "Extremely beautiful and delicate.", s: "Beautiful", a: "Ugly" },
    { w: "Extend", d: "Make longer or larger in space.", s: "Lengthen", a: "Shorten" },
    { w: "Extol", d: "Praise enthusiastically or highly.", s: "Acclaim", a: "Condemn" },
    { w: "Extra", d: "Added to an existing amount space.", s: "Additional", a: "Sparse" },
    { w: "Extract", d: "Remove or take out by effort.", s: "Remove", a: "Insert" },
    { w: "Extradite", d: "Hand over a person accused of crime.", s: "Deport", a: "Welcome" },
    { w: "High", d: "Great or extreme in degree level.", s: "Extreme", a: "Mild" },
    { w: "Exult", d: "Show or feel triumphant joy.", s: "Rejoice", a: "Mourn" },
    { w: "Eye", d: "The organ of sight in humans.", s: "Sight", a: "None" },
    { w: "Fable", d: "A short story conveying a moral.", s: "Tale", a: "Fact" },
    { w: "Fabric", d: "Cloth or other material produced.", s: "Cloth", a: "None" },
    { w: "Fabricate", d: "Construct or manufacture something.", s: "Build", a: "Destroy" },
    { w: "Facade", d: "The principal front of a building.", s: "Front", a: "Back" },
    { w: "Face", d: "The front part of a person's head.", s: "Visage", a: "None" },
    { w: "Facet", d: "One side of a many-sided gemstone.", s: "Aspect", a: "None" },
    { w: "Facilitate", d: "Make an action or process easy.", s: "Ease", a: "Obstruct" },
    { w: "Facility", d: "A building built for a purpose.", s: "Center", a: "None" },
    { w: "Fact", d: "A thing that is known to be true.", s: "Reality", a: "Fiction" },
    { w: "Factor", d: "A circumstance that contributes.", s: "Element", a: "None" },
    { w: "Faculty", d: "An inherent mental or physical power.", s: "Ability", a: "Inability" },
    { w: "Fade", d: "Gradually grow or make faint.", s: "Diminish", a: "Brighten" },
    { w: "Fail", d: "Be unsuccessful in an endeavor.", s: "Flop", a: "Succeed" },
    { w: "Faint", d: "Lacking in clarity or intensity.", s: "Dim", a: "Strong" },
    { w: "Fair", d: "Treating people equally or justly.", s: "Just", a: "Unfair" },
    { w: "Faith", d: "Complete trust or confidence in.", s: "Trust", a: "Doubt" },
    { w: "Fake", d: "Not genuine; counterfeit or imitation.", s: "False", a: "Real" },
    { w: "Falcon", d: "A quick bird of prey with long wings.", s: "Raptor", a: "None" },
    { w: "Fall", d: "Move downward rapidly of gravity.", s: "Descend", a: "Ascend" },
    { w: "Fallacy", d: "A mistaken belief, based on unsound.", s: "Myth", a: "Truth" },
    { w: "False", d: "Not in accordance with truth or fact.", s: "Incorrect", a: "True" },
    { w: "Fame", d: "The state of being known by many.", s: "Celebrity", a: "Obscurity" },
    { w: "Familiar", d: "Well known from long association.", s: "Common", a: "Strange" },
    { w: "Family", d: "A group of parents and their children.", s: "Household", a: "None" },
    { w: "Famine", d: "Extreme scarcity of nourishing food.", s: "Starvation", a: "Abundance" },
    { w: "Famous", d: "Known about by many people.", s: "Celebrated", a: "Unknown" },
    { w: "Fan", d: "An apparatus with rotating blades.", s: "Cooler", a: "Heater" },
    { w: "Fancy", d: "Elaborately decorated or sophisticated.", s: "Elegant", a: "Plain" },
    { w: "Fantasy", d: "The faculty of imagining impossible.", s: "Imagination", a: "Reality" },
    { w: "Farce", d: "A comic dramatic work using buffoonery.", s: "Comedy", a: "Tragedy" },
    { w: "Fare", d: "The money a passenger on transport pays.", s: "Price", a: "None" },
    { w: "Farm", d: "An area of land used for growing crops.", s: "Homestead", a: "None" },
    { w: "Farther", d: "At or to a greater distance.", s: "Further", a: "Closer" },
    { w: "Fascinate", d: "Attract the intense interest of.", s: "Charm", a: "Bore" },
    { w: "Fashion", d: "A popular trend, especially in dress.", s: "Style", a: "None" },
    { w: "Fast", d: "Moving or capable of moving at high speed.", s: "Quick", a: "Slow" },
    { w: "Fasten", d: "Close or join securely together.", s: "Secure", a: "Loose" },
    { w: "Fatal", d: "Causing death or absolute ruin.", s: "Deadly", a: "Harmless" },
    { w: "Fate", d: "The development of events beyond control.", s: "Destiny", a: "Choice" },
    { w: "Father", d: "A male parent of a child.", s: "Dad", a: "Son" },
    { w: "Fathom", d: "Understand a difficult problem.", s: "Comprehend", a: "Misinterpret" },
    { w: "Fatigue", d: "Extreme tiredness resulting from effort.", s: "Weariness", a: "Vigor" },
    { w: "Fault", d: "An attractive defect or imperfection.", s: "Flaw", a: "Virtue" },
    { w: "Favor", d: "An act of kindness beyond what is due.", s: "Kindness", a: "Disservice" },
    { w: "Favorable", d: "Expressing approval or giving advantage.", s: "Pleasible", a: "Dire" },
    { w: "Fawn", d: "A young deer in its first year.", s: "Deer", a: "None" },
    { w: "Fear", d: "An unpleasant emotion caused by threat.", s: "Terror", a: "Courage" },
    { w: "Feast", d: "A large meal, typically a celebratory.", s: "Banquet", a: "Snack" },
    { w: "Feather", d: "The light flat structures covering birds.", s: "Plume", a: "None" },
    { w: "Feature", d: "A distinctive attribute or aspect.", s: "Attribute", a: "None" },
    { w: "Federal", d: "Relating to a central government.", s: "National", a: "Local" },
    { w: "Fee", d: "A payment made to a professional body.", s: "Price", a: "None" },
    { w: "Feeble", d: "Lacking physical strength, as from age.", s: "Weak", a: "Strong" },
    { w: "Feed", d: "Give food to a person or animal.", s: "Nurture", a: "Starve" },
    { w: "Feel", d: "Be aware of a person through touch.", s: "Sense", a: "None" },
    { w: "Felicity", d: "Intense happiness and joy.", s: "Bliss", a: "Misery" },
    { w: "Feline", d: "Of or relating to the cat family.", s: "Cat", a: "Canine" },
    { w: "Fellow", d: "A man or boy companion.", s: "Comrade", a: "Rival" },
    { w: "Feminine", d: "Having qualities associated with women.", s: "Womanly", a: "Masculine" },
    { w: "Fence", d: "A wooden barrier enclosing an area.", s: "Barrier", a: "None" },
    { w: "Feral", d: "In a wild state, especially after escape.", s: "Wild", a: "Tame" },
    { w: "Ferment", d: "Undergo chemical change by yeast.", s: "Brew", a: "None" },
    { w: "Fern", d: "A flowerless plant which has feathery fronds.", s: "Frond-plant", a: "None" },
    { w: "Ferocious", d: "Savagery, fierce, cruel, or aggressive.", s: "Fierce", a: "Tame" },
    { w: "Fervent", d: "Having or showing a passionate intensity.", s: "Ardent", a: "Indifferent" },
    { w: "Festival", d: "A day or period of celebration.", s: "Gala", a: "None" },
    { w: "Fetch", d: "Go for and bring back someone or thing.", s: "Retrieve", a: "Drop" },
    { w: "Feud", d: "A prolonged state of active hostility.", s: "Conflict", a: "Peace" },
    { w: "Fever", d: "An abnormally high body temperature.", s: "Warmth", a: "None" },
    { w: "Few", d: "A small number of people or things.", s: "Sparse", a: "Many" },
    { w: "Fiasce", d: "A complete and ignominious failure.", s: "Disaster", a: "Triumph" },
    { w: "Fiber", d: "A thread or filament from which material is formed.", s: "Thread", a: "None" },
    { w: "Fickle", d: "Changing frequently, especially in loyalty.", s: "Variable", a: "Constant" },
    { w: "Fiction", d: "Literature that describes imaginary events.", s: "Story", a: "Fact" },
    { w: "Fidelity", d: "Faithfulness to a person, cause, or belief.", s: "Loyalty", a: "Treason" },
    { w: "Field", d: "An area of open land, especially grass.", s: "Meadow", a: "Desert" },
    { w: "Fierce", d: "Having or displaying an intense aggression.", s: "Ferocious", a: "Tame" },
    { w: "Fiery", d: "Consisting of fire or burning strongly.", s: "Burning", a: "Icy" },
    { w: "Fiesta", d: "An event of festivities or celebration.", s: "Festival", a: "None" }
  ];

  // Merge extraVocabulary into inflated, retaining only unique genuine words that contain only alphabetic characters
  const addedSet = new Set<string>();
  const finalUniqueList: CuratedWordItem[] = [];

  const addWordIfValid = (w: string, d: string, s: string, a: string) => {
    const cleanWord = w.trim();
    // Verify word only contains alphabetic characters (no spaces, numbers, symbols)
    if (!/^[a-zA-Z]+$/.test(cleanWord)) return;
    
    const token = cleanWord.toUpperCase();
    if (!addedSet.has(token)) {
      addedSet.add(token);
      finalUniqueList.push({
        word: cleanWord,
        definition: d.trim(),
        synonyms: [s.trim()],
        antonyms: [a.trim()]
      });
    }
  };

  // Add inflated initially
  for (const item of inflated) {
    addWordIfValid(item.word, item.definition, item.synonyms[0], item.antonyms[0]);
  }

  // Add extraVocabulary
  for (const item of extraVocabulary) {
    addWordIfValid(item.w, item.d, item.s, item.a);
  }

  return finalUniqueList;
}

export const CURATED_WORDS: CuratedWordItem[] = generate1000Words();

export const CURATED_WORDS_MAP = new Map<string, CuratedWordItem>(
  CURATED_WORDS.map(item => [item.word.toUpperCase(), item])
);
